-- Initial Schema for TASUKI v8.5 Requirements
-- Generated by Codex (Antigravity Agent) based on docs/TASUKI_database_schema.md

-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: organizations
CREATE TABLE IF NOT EXISTS public.organizations (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    name text NOT NULL,
    plan text DEFAULT 'free' NOT NULL,
    billing_meta jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: stores
CREATE TABLE IF NOT EXISTS public.stores (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE NOT NULL,
    name text NOT NULL,
    timezone text DEFAULT 'Asia/Tokyo' NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: users (Profiles linked to auth.users)
CREATE TABLE IF NOT EXISTS public.users (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    display_name text,
    language text DEFAULT 'ja' NOT NULL,
    meta jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: memberships
CREATE TABLE IF NOT EXISTS public.memberships (
    user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
    store_id uuid REFERENCES public.stores(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('owner', 'manager', 'staff')),
    status text DEFAULT 'invited' NOT NULL CHECK (status IN ('active', 'invited', 'disabled')),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (user_id, store_id)
);

-- Table: handovers (Flow)
CREATE TABLE IF NOT EXISTS public.handovers (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    store_id uuid REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    author_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
    mux_asset_id text,
    hls_url text,
    thumbnail_url text,
    ai_status text DEFAULT 'pending_upload' NOT NULL CHECK (ai_status IN ('pending_upload', 'uploaded', 'ready_for_ai', 'ai_running', 'draft_created', 'failed')),
    local_offline_flag boolean DEFAULT false NOT NULL,
    captured_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: manuals (Stock)
CREATE TABLE IF NOT EXISTS public.manuals (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    handover_id uuid REFERENCES public.handovers(id) ON DELETE SET NULL,
    store_id uuid REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    status text DEFAULT 'draft' NOT NULL CHECK (status IN ('draft', 'published')),
    source_type text DEFAULT 'ai' NOT NULL CHECK (source_type IN ('ai', 'legacy_import', 'manual')),
    original_doc_url text,
    category text,
    ai_summary text,
    ai_steps jsonb,
    ai_tips jsonb,
    approved_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
    published_at timestamp with time zone,
    imported_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: ai_jobs
CREATE TABLE IF NOT EXISTS public.ai_jobs (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    handover_id uuid REFERENCES public.handovers(id) ON DELETE CASCADE NOT NULL,
    stage text NOT NULL,
    retries integer DEFAULT 0 NOT NULL,
    error_code text,
    payload jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: manual_edits
CREATE TABLE IF NOT EXISTS public.manual_edits (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    manual_id uuid REFERENCES public.manuals(id) ON DELETE CASCADE NOT NULL,
    editor_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
    edit_start_at timestamp with time zone,
    edit_end_at timestamp with time zone,
    diff_summary jsonb
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.handovers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manuals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manual_edits ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- RLS Policies
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. users Policies
-- ------------------------------------------------------------------------------
-- Allow users to read themselves
CREATE POLICY "users_read_self" ON public.users
FOR SELECT TO authenticated
USING (auth.uid() = id);

-- Allow users to read other users in the same store (via memberships)
CREATE POLICY "users_read_store_members" ON public.users
FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM memberships m1
        JOIN memberships m2 ON m1.store_id = m2.store_id
        WHERE m1.user_id = auth.uid()
          AND m2.user_id = users.id
          AND m1.status = 'active'
    )
);

-- Allow update self
CREATE POLICY "users_update_self" ON public.users
FOR UPDATE TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- ------------------------------------------------------------------------------
-- 2. organizations Policies
-- ------------------------------------------------------------------------------
-- Read: Members of any store in the organization
CREATE POLICY "organizations_read_policy" ON public.organizations
FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM stores s
        JOIN memberships m ON s.id = m.store_id
        WHERE s.organization_id = organizations.id
          AND m.user_id = auth.uid()
          AND m.status = 'active'
    )
);

-- ------------------------------------------------------------------------------
-- 3. stores Policies
-- ------------------------------------------------------------------------------
-- Read: Members of the store
CREATE POLICY "stores_read_policy" ON public.stores
FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.store_id = stores.id
          AND m.user_id = auth.uid()
          AND m.status = 'active'
    )
);

-- Update: Owners only
CREATE POLICY "stores_update_policy" ON public.stores
FOR UPDATE TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.store_id = stores.id
          AND m.user_id = auth.uid()
          AND m.role = 'owner'
          AND m.status = 'active'
    )
);

-- ------------------------------------------------------------------------------
-- 4. memberships Policies
-- ------------------------------------------------------------------------------
-- Read: Members of the same store
CREATE POLICY "memberships_read_policy" ON public.memberships
FOR SELECT TO authenticated
USING (
    store_id IN (
        SELECT store_id FROM memberships
        WHERE user_id = auth.uid() AND status = 'active'
    )
);

-- Insert: Owner/Manager can add members
CREATE POLICY "memberships_insert_policy" ON public.memberships
FOR INSERT TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM memberships
        WHERE user_id = auth.uid()
          AND store_id = memberships.store_id
          AND role IN ('owner', 'manager')
          AND status = 'active'
    )
);

-- Update: Owner can update roles
CREATE POLICY "memberships_update_policy" ON public.memberships
FOR UPDATE TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM memberships
        WHERE user_id = auth.uid()
          AND store_id = memberships.store_id
          AND role = 'owner'
          AND status = 'active'
    )
);

-- ------------------------------------------------------------------------------
-- 5. handovers Policies
-- ------------------------------------------------------------------------------
-- Read: Members of the same store
CREATE POLICY "handovers_read_policy" ON public.handovers
FOR SELECT TO authenticated
USING (
    store_id IN (
        SELECT store_id FROM memberships
        WHERE user_id = auth.uid() AND status = 'active'
    )
);

-- Insert: Members of the same store (anyone can upload Flow)
CREATE POLICY "handovers_insert_policy" ON public.handovers
FOR INSERT TO authenticated
WITH CHECK (
    store_id IN (
        SELECT store_id FROM memberships
        WHERE user_id = auth.uid() AND status = 'active'
    )
    AND author_id = auth.uid()
);

-- Update: Author OR Manager/Owner
CREATE POLICY "handovers_update_policy" ON public.handovers
FOR UPDATE TO authenticated
USING (
    author_id = auth.uid()
    OR
    EXISTS (
        SELECT 1 FROM memberships
        WHERE user_id = auth.uid()
          AND store_id = handovers.store_id
          AND role IN ('owner', 'manager')
          AND status = 'active'
    )
);

-- ------------------------------------------------------------------------------
-- 6. manuals Policies
-- ------------------------------------------------------------------------------
-- Read:
-- 1. Manager/Owner can see all (including draft)
-- 2. Staff can see only published
CREATE POLICY "manuals_read_policy" ON public.manuals
FOR SELECT TO authenticated
USING (
    (
        -- Is Manager/Owner?
        EXISTS (
            SELECT 1 FROM memberships
            WHERE user_id = auth.uid()
              AND store_id = manuals.store_id
              AND role IN ('owner', 'manager')
              AND status = 'active'
        )
    )
    OR
    (
        -- Is Staff AND Manual is published AND belongs to store?
        status = 'published'
        AND
        EXISTS (
            SELECT 1 FROM memberships
            WHERE user_id = auth.uid()
              AND store_id = manuals.store_id
              AND status = 'active'
        )
    )
);

-- Insert: Manager/Owner only
CREATE POLICY "manuals_insert_policy" ON public.manuals
FOR INSERT TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM memberships
        WHERE user_id = auth.uid()
          AND store_id = manuals.store_id
          AND role IN ('owner', 'manager')
          AND status = 'active'
    )
);

-- Update: Manager/Owner only
CREATE POLICY "manuals_update_policy" ON public.manuals
FOR UPDATE TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM memberships
        WHERE user_id = auth.uid()
          AND store_id = manuals.store_id
          AND role IN ('owner', 'manager')
          AND status = 'active'
    )
);

-- ------------------------------------------------------------------------------
-- 7. ai_jobs Policies
-- ------------------------------------------------------------------------------
-- Read: Manager/Owner
CREATE POLICY "ai_jobs_read_policy" ON public.ai_jobs
FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM handovers h
        JOIN memberships m ON h.store_id = m.store_id
        WHERE h.id = ai_jobs.handover_id
          AND m.user_id = auth.uid()
          AND m.role IN ('owner', 'manager')
          AND m.status = 'active'
    )
);

-- ------------------------------------------------------------------------------
-- 8. manual_edits Policies
-- ------------------------------------------------------------------------------
-- Read: Manager/Owner
CREATE POLICY "manual_edits_read_policy" ON public.manual_edits
FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM manuals mn
        JOIN memberships m ON mn.store_id = m.store_id
        WHERE mn.id = manual_edits.manual_id
          AND m.user_id = auth.uid()
          AND m.role IN ('owner', 'manager')
          AND m.status = 'active'
    )
);

-- Insert: Manager/Owner (Triggered by app logic when editing)
CREATE POLICY "manual_edits_insert_policy" ON public.manual_edits
FOR INSERT TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM manuals mn
        JOIN memberships m ON mn.store_id = m.store_id
        WHERE mn.id = manual_edits.manual_id
          AND m.user_id = auth.uid()
          AND m.role IN ('owner', 'manager')
          AND m.status = 'active'
    )
);
